"""Initial migration.

Revision ID: 47734b03d901
Revises: 
Create Date: 2022-08-06 14:05:40.475074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47734b03d901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subwayline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subwayline')
    # ### end Alembic commands ###
