"""Update models to match expected format

Revision ID: a8623e3a6a06
Revises: b1e2b7dca9cc
Create Date: 2022-08-09 11:26:28.256621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8623e3a6a06'
down_revision = 'b1e2b7dca9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('censusblock', sa.Column('boroname', sa.String(length=140), nullable=False))
    op.add_column('subwaystation', sa.Column('routes', sa.String(length=140), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subwaystation', 'routes')
    op.drop_column('censusblock', 'boroname')
    # ### end Alembic commands ###
