"""Add CensusBlock and Street models

Revision ID: b1e2b7dca9cc
Revises: 6c66fe5f2ad1
Create Date: 2022-08-06 15:50:18.664667

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = 'b1e2b7dca9cc'
down_revision = '6c66fe5f2ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('censusblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.String(length=255), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=26918, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('popn_total', sa.Integer(), nullable=True),
    sa.Column('popn_white', sa.Integer(), nullable=True),
    sa.Column('popn_black', sa.Integer(), nullable=True),
    sa.Column('popn_asian', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id')
    )
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geom', Geometry(geometry_type='MULTILINESTRING', srid=26918, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('street')
    op.drop_table('censusblock')
    # ### end Alembic commands ###
